# Generated by Django 4.2 on 2023-04-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название места"),
                ),
                (
                    "description_short",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                ("description_long", models.TextField(verbose_name="Полное описание")),
                ("lng", models.FloatField(null=True, verbose_name="Долгота")),
                ("lat", models.FloatField(null=True, verbose_name="Широта")),
            ],
        ),
    ]
