# Generated by Django 4.2 on 2023-04-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="number",
            field=models.IntegerField(null=True, verbose_name="Номер картинки"),
        ),
    ]
